security:
  oauth2:
    client:
      # server 中配置的信息
      clientId: demo2
      clientSecret: demo2
      # 用户请求授权回调地址
      user-authorization-uri: http://127.0.0.1:9999/server/oauth/authorize
      # 用户换区 jwt token 地址
      access-token-uri: http://127.0.0.1:9999/server/oauth/token
    resource:
      jwt:
        # 秘钥地址
        key-uri: http://127.0.0.1:9999/server/oauth/token_key
server:
  port: 8081
  servlet:
    context-path: /product
