spring:
  session:
    store-type: none
  datasource:
    url: jdbc:mysql://47.105.218.58/wtf?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 158262751
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  #
  #  thymeleaf:
  #    cache: false
  #    prefix: classpath:/templates/
  #    suffix: .html
  redis:
    jedis:
      pool:
        min-idle: 5
        max-active: 10
        max-idle: 10
        max-wait: 2000ms #连接池等待时间
    host: 47.105.218.58
    port: 6379
    timeout: 1000ms #连接时间
  # 传时间戳
  jackson:
    serialization:
      write-dates-as-timestamps: true

# 配置请求登录界面
com:
  security:
    browser:
      loginPage: /index.html
    #      配置请求成功后返回 HTML 还是 JSON
    #      loginType: REDIRECT
    social:
      qq:
        #        申请
        app-id:
        app-secret: