spring:
  session:
    store-type: none
  datasource:
    url: jdbc:mysql://47.105.218.58/qq?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 158262751
    #    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  #
  #  thymeleaf:
  #    cache: false
  #    prefix: classpath:/templates/
  #    suffix: .html
  redis:
    jedis:
      pool:
        min-idle: 5
        max-active: 10
        max-idle: 10
        max-wait: 2000ms #连接池等待时间
    host: 47.105.218.58
    port: 6379
    timeout: 1000ms #连接时间
  # 传时间戳
  jackson:
    serialization:
      write-dates-as-timestamps: true
# 配置请求登录界面
com:
  security:
    browser:
      loginPage: /demo-index.html
      #      配置 JSON 还是重定向 REDIRECT
      loginType: JSON
      # qq 授权后的登录页面
      signUrl: /demo-sign.html
    # 配置验证码默认级别的配置
    validateCode:
      imageCode:
        length: 1
        width: 200
        # 配置一定要加 ，URL地址一定会被验证码拦截
      #         url: /user,/user/*
      smsCode:
        length: 6
    # 网站回调域名 www.pinzhi365.com/qqLogin/callback.do QQ 互联的应用网站配置
    social:
      # QQ 登录会访问 //qqLogin
      filterProcessesUrl: /login
      qq:
        #  申请
        app-id: 101581644
        app-secret: 9364692f2f218d8a8d0dadf2dcb978c6
        providerId: qq
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4

# 必须以 80 端口，当然有自己的域名也可以
server:
  port: 8080
  servlet:
    session:
      # TomcatServletWebServerFactory#configureSession 查看 Tomcat 上下文信息
      timeout: 10 # session 超时时间设置，在SpringBoot 最少的超时时间为 1 m