spring:
  redis:
    jedis:
      pool:
        min-idle: 5
        max-active: 10
        max-idle: 10
        max-wait: 2000ms #连接池等待时间
    host: ${linux.port.base}
    port: 6379
    timeout: 1000ms #连接时间